### ISSUE TITLE
aegea has a lot of old requirements

### ISSUE THREAD

**Issue by jamestwebber** [kislyuk/aegea#43] opened 2018-10-06 00:03 UTC
These are starting to become an issue as they get older. For instance, it requires the `typing` package which conflicts with Python's built-in typing module, breaking it. It also prevents lots of things from being updated. Basically it has to be in its own little environment which is pretty inconvenient for a command-line tool.

**Comment by kislyuk** [comment] 2018-10-06 02:00
I've looked through the dependencies for aegea and the only one that is pinned to a version range below the most recent is tweak, which I will update.

I'm confused about the issues that you are experiencing. The `typing` module is supposed to be a no-op on Python 3.4+ (as described in https://pypi.org/project/typing/). Can you give me the specifics of the issues that you are encountering?

**Comment by kislyuk** [comment] 2018-10-06 02:04
Relaxed tweak version range in v2.2.5.

**Comment by kislyuk** [comment] 2018-10-06 02:08
The `typing` module and other dependencies are transitive to the dependency on `chalice`, which is not required for most of the features of aegea. So I've moved that dependency to be optional. It won't be installed by default now, and requires running `pip install aegea[awslambda]` to install.

Released in v2.2.6.

**Comment by kislyuk** [comment] 2018-10-06 03:51
OK so the issue is just with `typing`?

**Comment by jamestwebber** [comment] 2018-10-06 04:06
That was the issue that caused me to make an issue, because it's the first case when aegea's requirements broke something I was doing. Most of the time it's just the cause of a lot of warning messages (e.g. warnings to update pip when you can't because of chalice). Having no warnings is nicer.

**Comment by kislyuk** [comment] 2018-10-06 05:31
OK. Closing this because no further action is needed.

**Closed by kislyuk** 2018-10-06 05:31 UTC
